/*https://projecteuler.net/problem=29
Distinct powers
Problem 29

Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

    2^2=4, 2^3=8, 2^4=16, 2^5=32
    3^2=9, 3^3=27, 3^4=81, 3^5=243
    4^2=16, 4^3=64, 4^4=256, 4^5=1024
    5^2=25, 5^3=125, 5^4=625, 5^5=3125

If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?*/

using System;
using System.Collections.Generic;

class Program {
    public static void Main() {
        //tricky part here is that some of the numbers may be duplicates, like the number 16
        //in the example above, so you can't use combinatorics (I think...).
	//We will the Contains() method of a list.
        List<double> results = new List<double>();
        for (double i = 2; i < 101; i++) {
            for (double j = 2; j < 101; j++) {
                if (!results.Contains(Math.Pow(i,j))) {
                    results.Add(Math.Pow(i,j));
                }
            }
        }
    Console.Write(results.Count.ToString() + "\n");
    }
}
