/*https://projecteuler.net/problem=12
Highly divisible triangular number
Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?*/

using System;

class Program {

	private static int findNumOfDivisors(int number) {
    		int numOfDivisors = 0;
    		int sqrt = (int) Math.Sqrt(number);

		//Use trial division to find all factors below sqrt(number).
    		for(int i = 1; i<= sqrt; i++){
        		if(number % i == 0){
				//Add 2 instead of 1, taking advantage of the fact that factors must be able to be expressed as p*q = number.
            			numOfDivisors += 2;
        		}
    		}


		//If number is a perfect square, take away one. Necessary because the same number got added twice in the loop before.
    		if (sqrt * sqrt == number) {
        		numOfDivisors--;
    	}	

    		return numOfDivisors;
	}

	private static void Main() {
		int currentTriangleNumber = 0;
		int i = 1;

		while(findNumOfDivisors(currentTriangleNumber) < 500){
    			currentTriangleNumber += i;
    			i++;
		}

		Console.Write(currentTriangleNumber.ToString() + "\n");
		//answer: 76576500
	}
}
